### ISSUE TITLE
Glitch Support.

### ISSUE THREAD

**Issue by azidanimoh** [zyrouge/zyrouge.gq#1]
**_deleted_**

**Comment by scientific-dev** [comment]
Copy paste mostly 
There might be some ways

**Comment by scientific-dev** [comment]
https://medium.com/glitch/import-code-from-anywhere-83fb60ea4875

I found this in google

**Comment by scientific-dev** [comment]
This issue opened for yrs -_-

**Comment by zyrouge** [comment]
uh this is just my website's code ._.

**Comment by scientific-dev** [comment]
I can;t yet understand his issue
Did he mean how to fork codes in glitch?
